project:
  type: website

website:
  title: "ISSS608-VAA"
  navbar:
    left:
      - text: "Hands-on_Exercise"
        menu:
          - text: "Hands-on_Exercise01"
            href: "Hands-on%20Ex/Hands-on%20Ex01/Hands-on%20Exercise01.html"
    right:
      - href: index.qmd
        text: Home
      - about.qmd


format:
  html:
    theme: morph
    css: styles.css
    toc: true

editor: visual

