project:
  type: website

website:
  title: "ISSS608-VAA"
  navbar:
    left:
      - text: "Hands-on_Exercise"
        menu:
          - text: "Hands-on_Exercise01"
            href: "Hands-on%20Ex/Hands-on%20Ex01/Hands-on%20Exercise01.html"
          - text: "Hands-on_Exercise02"
            href: "Hands-on%20Ex/Hands-on%20Ex02/Hands-on%20Exercise02.html"
    right:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About


format:
  html:
    theme: morph
    css: styles.css
    toc: true

editor: visual

