project:
  type: website
  output-dir: docs

website:
  title: "ISSS608-VAA"
  navbar:
    left:
      - text: "Hands-on_Exercise"
        menu:
          - text: "Hands-on_Exercise01"
            href: "Hands-on_Ex/Hands-on_Ex01/Hands-on_Exercise01.html"
          - text: "Hands-on_Exercise02"
            href: "Hands-on_Ex/Hands-on_Ex02/Hands-on_Exercise02.html"
          - text: "Hands-on_Exercise03"
            href: "Hands-on_Ex/Hands-on_Ex03/Hands-on_Exercise03.html"  
          - text: "Hands-on_Exercise04"
            href: "Hands-on_Ex/Hands-on_EX04/Hands-on_Exercise04.html"
    right:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About


format:
  html:
    theme: morph
    css: styles.css
    toc: true

editor: visual

